#folders
# MUST BE ABSOLUTE PATH
WORKSPACE_ROOT='/home/dae/planet-war/workspace/'
SUBMISSION_ROOT=WORKSPACE_ROOT+'submissions/'
MATCH_ROOT=WORKSPACE_ROOT+'matches/'
MAP_FOLDER=WORKSPACE_ROOT+'maps/'
LOG_FOLDER=WORKSPACE_ROOT+'log/'


#match parameter
TURN_LIMIT = 200
NOOP_SUBMISSION_ID = 1
NAIVE_SUBMISSION_ID = 2
